---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# jpcovid19

<!-- badges: start -->
<!-- badges: end -->

世界各地で深刻化している新型コロナウイルス感染症（COVID-19）に関するデータ処理および可視化を補助するRパッケージです。

## インストール

CRAN登録は行わないため、パッケージはGitHubを経由してインストールしてください。

``` r
install.packages("remotes")
remotes::install_github("tokyor/jpcovid19")
```

## デモ

```{r example}
library(jpcovid19)
```

### `read_yds_visitor()`

ヤフー・データソリューション https://ds.yahoo.co.jp/ が提供する「全国主要都市来訪者・往訪者推移指数オープンデータ」をRで扱いやすい形式として読み込みます。

```{r, eval=FALSE, echo=TRUE}
#  デフォルトで「比較日対応表」（カレンダー）を除いた全てのシートを対象
read_yds_visitor("come_in_index_japan.xlsx")
#> # A tibble: 122 x 141
#>    日付       北海道全域 札幌市 札幌市中央区 青森県全域 青森市 岩手県全域 盛岡市
#>    <date>          <dbl>  <dbl>        <dbl>      <dbl>  <dbl>      <dbl>  <dbl>
#>  1 2020-01-01        104     82           76         92     85         92     86
#>  2 2020-01-02        110     98          103        121    108        112    100
#>  3 2020-01-03        115     93           73        132    104        133     97
#>  4 2020-01-04        114    104           97        131    118        120    101
#>  5 2020-01-05        106    101          103        128    127        102    103
#>  6 2020-01-06        108     99          101        116    104         93     99
#>  7 2020-01-07        111     97          101        110    102         90    102
#>  8 2020-01-08        105     99          102        104    102         92     96
#>  9 2020-01-09        101     94          100        101     97         91     97
#> 10 2020-01-10        102     99          101        100     95         92     97
#> # … with 112 more rows, and 133 more variables: 宮城県全域 <dbl>,
#> #   仙台市 <dbl>, 仙台市青葉区 <dbl>, 秋田県全域 <dbl>, 秋田市 <dbl>,
#> #   山形県全域 <dbl>, 山形市 <dbl>, 福島県全域 <dbl>, 福島市 <dbl>,
#> #   茨城県全域 <dbl>, 水戸市 <dbl>, 栃木県全域 <dbl>, 宇都宮市 <dbl>,
#> #   群馬県全域 <dbl>, 前橋市 <dbl>, 埼玉県全域 <dbl>, さいたま市 <dbl>,
#> #   さいたま市大宮区 <dbl>, 千葉県全域 <dbl>, 千葉市 <dbl>, 千葉市中央区 <dbl>,
#> #   東京都全域 <dbl>, 千代田区 <dbl>, 中央区 <dbl>, 港区 <dbl>, 新宿区 <dbl>,
#> #   文京区 <dbl>, 台東区 <dbl>, 墨田区 <dbl>, 江東区 <dbl>, 品川区 <dbl>,
#> #   目黒区 <dbl>, 大田区 <dbl>, 世田谷区 <dbl>, 渋谷区 <dbl>, 中野区 <dbl>,
#> #   杉並区 <dbl>, 豊島区 <dbl>, 北区 <dbl>, 荒川区 <dbl>, 板橋区 <dbl>,
#> #   練馬区 <dbl>, 足立区 <dbl>, 葛飾区 <dbl>, 江戸川区 <dbl>,
#> #   神奈川県全域 <dbl>, 横浜市 <dbl>, 横浜市西区 <dbl>, 川崎市 <dbl>,
#> #   川崎市川崎区 <dbl>, 相模原市 <dbl>, 相模原市緑区 <dbl>, 新潟県全域 <dbl>,
#> #   新潟市 <dbl>, 新潟市中央区 <dbl>, 富山県全域 <dbl>, 富山市 <dbl>,
#> #   石川県全域 <dbl>, 金沢市 <dbl>, 福井県全域 <dbl>, 福井市 <dbl>,
#> #   山梨県全域 <dbl>, 甲府市 <dbl>, 長野県全域 <dbl>, 長野市 <dbl>,
#> #   岐阜県全域 <dbl>, 岐阜市 <dbl>, 静岡県全域 <dbl>, 静岡市 <dbl>,
#> #   静岡市葵区 <dbl>, 浜松市 <dbl>, 浜松市中区 <dbl>, 愛知県全域 <dbl>,
#> #   名古屋市 <dbl>, 名古屋市中区 <dbl>, 三重県全域 <dbl>, 津市 <dbl>,
#> #   滋賀県全域 <dbl>, 大津市 <dbl>, 京都府全域 <dbl>, 京都市 <dbl>,
#> #   大阪府全域 <dbl>, 大阪市 <dbl>, 大阪市北区 <dbl>, 堺市 <dbl>,
#> #   堺市堺区 <dbl>, 兵庫県全域 <dbl>, 神戸市 <dbl>, 神戸市中央区 <dbl>,
#> #   奈良県全域 <dbl>, 奈良市 <dbl>, 和歌山県全域 <dbl>, 和歌山市 <dbl>,
#> #   鳥取県全域 <dbl>, 鳥取市 <dbl>, 島根県全域 <dbl>, 松江市 <dbl>,
#> #   岡山県全域 <dbl>, 岡山市 <dbl>, 岡山市北区 <dbl>, …

# シート番号指定での読み込み
read_yds_visitor("come_in_index_japan.xlsx", sheet = c(1, 3))
#> # A tibble: 122 x 6
#>    日付       北海道全域 札幌市 札幌市中央区 岩手県全域 盛岡市
#>    <date>          <dbl>  <dbl>        <dbl>      <dbl>  <dbl>
#>  1 2020-01-01        104     82           76         92     86
#>  2 2020-01-02        110     98          103        112    100
#>  3 2020-01-03        115     93           73        133     97
#>  4 2020-01-04        114    104           97        120    101
#>  5 2020-01-05        106    101          103        102    103
#>  6 2020-01-06        108     99          101         93     99
#>  7 2020-01-07        111     97          101         90    102
#>  8 2020-01-08        105     99          102         92     96
#>  9 2020-01-09        101     94          100         91     97
#> 10 2020-01-10        102     99          101         92     97
#> # … with 112 more rows
```

この関数では読み込んだデータを縦長形式に変換するオプションを備えています。

```{r, eval=FALSE, echo=TRUE}
# 縦長に変換
read_yds_visitor("go_out_index_japan.xlsx", long = TRUE)
#> # A tibble: 17,080 x 3
#>    date       area         value
#>    <date>     <chr>        <dbl>
#>  1 2020-01-01 北海道全域      86
#>  2 2020-01-01 札幌市          89
#>  3 2020-01-01 札幌市中央区    96
#>  4 2020-01-01 青森県全域      88
#>  5 2020-01-01 青森市          89
#>  6 2020-01-01 岩手県全域      85
#>  7 2020-01-01 盛岡市          93
#>  8 2020-01-01 宮城県全域      90
#>  9 2020-01-01 仙台市          91
#> 10 2020-01-01 仙台市青葉区    88
#> # … with 17,070 more rows

```

なおこのデータを用いて出典（ヤフー・データソリューション）を明示するよう、お願いします。





